### ISSUE TITLE
Product cart details are not showing under Description section for Lead.

### ISSUE THREAD

**Issue by Chetna1510** [TycheSoftwares/Salesforce-CRM-for-Abandoned-Cart#47]
I have installed WordPress 5.0-RC1 and activated "Salesforce CRM Sync for WooCommerce Abandoned Cart Plugin" add-on version 1.0 on woo_chetna. Abandoned Cart Pro for WooCommerce plugin version is 7.11.0 and WooCommerce version is 3.5.1.

I have sent one abandoned cart which was tracked by add to cart popup modal. It was successfully added to Salesforce CRM. But it doesn't show Product cart details.

Screenshot of Abandoned Orders: http://prntscr.com/ln3wml
Screenshot of Salesforce CRM: http://prntscr.com/ln5txd

It is a simple product.

**Comment by dhruvintyche** [comment]
Fixed in https://github.com/TycheSoftwares/Salesforce-CRM-for-Abandoned-Cart/commit/6da3d63898655da8a8596afae642ae794e8c9728
