### ISSUE TITLE
Abandoned Cart Data are not adding into the Contact List when I have selected Contact

### ISSUE THREAD

**Issue by Chetna1510** [TycheSoftwares/Salesforce-CRM-for-Abandoned-Cart#50]
Abandoned Cart Data are not adding into the Contact List when I have selected Contact in "Export abandoned cart data as" setting.

Screenshot of AC page: http://prntscr.com/lng2v3
SalesForce CRM: http://prntscr.com/lng30o

**Comment by dhruvintyche** [comment]
Fixed in https://github.com/TycheSoftwares/Salesforce-CRM-for-Abandoned-Cart/commit/6da3d63898655da8a8596afae642ae794e8c9728
