### ISSUE TITLE
Facing a problem with the Salesforce Addon set up.

### ISSUE THREAD

**Issue by priyanka-tychesoftwares** [TycheSoftwares/Salesforce-CRM-for-Abandoned-Cart#52]
**Describe the bug**
Facing a problem with the Salesforce Addon set up.

**To Reproduce**
1. I have created an account here: https://www.salesforce.com/
2. Added a Salesforce Username, password, and the Security Token of my account.
3. When I clicked on the Test Connection link, it is neither showing a successful message or a Failed message.

Video: https://www.screencast.com/t/nLdGbhXTj

**Comment by pinalj** [comment]
The setup works fine when checking with a developer account. Please create a developer account at developer.salesforce.com

**Comment by apeksha10** [comment]
This is an invalid issue. Hence I have put a fixed label.
