### ISSUE TITLE
Getting a fatal error on activating the Salesforce CRM Sync addon.

### ISSUE THREAD

**Issue by priyanka-tychesoftwares** [TycheSoftwares/Salesforce-CRM-for-Abandoned-Cart#54]
Getting a fatal error on activating the Salesforce CRM Sync addon.

Error log:

Fatal error: Uncaught Error: Class 'SoapClient' not found in /var/www/html/wp-content/plugins/salesforce-crm-for-abandoned-cart/soapclient/SforcePartnerClient.php:44 Stack trace: #0 /var/www/html/wp-content/plugins/salesforce-crm-for-abandoned-cart/salesforce-crm-for-abandoned-cart.php(38): require_once() #1 /var/www/html/wp-admin/includes/plugin.php(2297): include('/var/www/html/w...') #2 /var/www/html/wp-admin/plugins.php(191): plugin_sandbox_scrape() #3 {main} thrown in /var/www/html/wp-content/plugins/salesforce-crm-for-abandoned-cart/soapclient/SforcePartnerClient.php on line 44

Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'class@anonymous' does not have a method 'shutdown_handler' in /var/www/html/wp-includes/class-wp-hook.php on line 287

Video: https://www.loom.com/share/3ef753243bf54010b694e4733f36827c

https://tychesoftwares.freshdesk.com/a/tickets/24237

**Comment by pinalj** [comment]
Unable to replicate the issue with the latest versions of WP, WC, AC pro and the GitHub copy of the addon

**Comment by apeksha10** [comment]
Unable to replicate the issue with the latest git copy of Salesforce addon and Abandoned Cart Pro plugin

Hence I have put a fixed label.
