### ISSUE TITLE
Product cart details are not showing under the Description section for Contact.

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/Salesforce-CRM-for-Abandoned-Cart#58]
Product cart details are not showing under the Description section for Contact.

I have sent one abandoned cart which was tracked by add to cart popup modal. It was successfully added to Salesforce CRM. But it doesn't show Product cart details.

Screenshot of Abandoned Orders: https://www.screencast.com/t/7tQgvSGLk9
Screenshot of Salesforce CRM: https://www.screencast.com/t/s8EU7wZ3s1P

Note: I abandoned the Variable product.
The same issue is replicated with a simple product.

**Comment by pinalj** [comment]
For contacts, product details are not mentioned in the description. They are shown in a popup in the Related tab itself: https://www.screencast.com/t/WxSF8m5d9

**Comment by apeksha10** [comment]
I think we should display product descriptions while editing the events.

Like the lead section, product information appears fine while editing the event.
see the video: https://www.screencast.com/t/OMagFAqi

@pinalj can you please check this is possible or not?

It is better to show product description 

Hence I have re-open this issue

**Comment by apeksha10** [comment]
Contact refers to a person so it doesn't make sense to see the abandoned info in the description and Lead refers to  a lead is an individual with no purchase history  a lead is an individual with no purchase history who expresses some interest in your product or service and provides their contact information

Hence the above issue is not a valid issue.

Hence I have closed the issue
